#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message='Ensuring downward compatibility...' --weight=1

if [ -z "${default_home_server:-}" ]; then
    default_home_server='matrix.org'
    ynh_app_setting_set --app=$app --key=default_home_server --value=$default_home_server
fi

if [ -z "${disable_custom_urls:-}" ]; then
    disable_custom_urls=false
    ynh_app_setting_set --app=$app --key=disable_custom_urls --value=$disable_custom_urls
fi

if [ -z "${disable_guests:-}" ]; then
    disable_guests=false
    ynh_app_setting_set --app=$app --key=disable_guests --value=$disable_guests
fi

if [ -z "${disable_3pid_login:-}" ]; then
    disable_3pid_login=false
    ynh_app_setting_set --app=$app --key=disable_3pid_login --value=$disable_3pid_login
fi

if [ -z "${default_country_code:-}" ]; then
    default_country_code=false
    ynh_app_setting_set --app=$app --key=default_country_code --value=$default_country_code
fi

if [ -z "${brand_text:-}" ]; then
    brand_text=Element
    ynh_app_setting_set --app=$app --key=brand_text --value=$brand_text
fi

if [ -z "${default_federate:-}" ]; then
    default_federate=true
    ynh_app_setting_set --app=$app --key=default_federate --value=$default_federate
fi

if [ -z "${default_theme:-}" ]; then
    default_theme=light
    ynh_app_setting_set --app=$app --key=default_theme --value=$default_theme
fi

if [ -z "${show_labs_settings:-}" ]; then
    show_labs_settings=false
    ynh_app_setting_set --app=$app --key=show_labs_settings --value=$show_labs_settings
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	# purge the "bundles" folder to avoid pointlessly taking up space at each update
	ynh_secure_remove --file="$install_dir/bundles/"

	ynh_script_progression --message="Upgrading source files..." --weight=1

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep="config.json"
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

configure_element

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
